name: Create DAST Scan

on:
  workflow_dispatch:

jobs:
  push-aws-ecr:
    runs-on: ubuntu-latest
    container:
      image: veracode/api-signing:latest
    env:
      VERACODE_API_KEY_ID: "${{ secrets.VERACODE_API_ID }}"
      VERACODE_API_KEY_SECRET: "${{ secrets.VERACODE_API_KEY }}"

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Run Veracode API Signing
        run: |
          echo "Using Veracode API Signing Image"
          http --auth-type=veracode_hmac POST "https://api.veracode.com/was/configservice/v1/analyses" < input.json
