name: Veracode DAST

on:
  workflow_dispatch:

jobs:
  Submit-DAST-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Submit Veracode DAST Scan
        uses: veracode-australia/veracode-dast-action@main
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
